function [ACCELEROMETERXms,ACCELEROMETERYms,ACCELEROMETERZms,GRAVITYXms,GRAVITYYms,GRAVITYZms,MAGNETICFIELDXT,MAGNETICFIELDYT,MAGNETICFIELDZT,ORIENTATIONZazimuth,ORIENTATIONXpitch,ORIENTATIONYroll,LOCATIONLatitude,LOCATIONLongitude,LOCATIONAltitudem,LOCATIONAltitudegooglem,LOCATIONSpeedKmh,LOCATIONAccuracym,LOCATIONORIENTATION,Satellitesinrange,Timesincestartinms,YYYYMODDHHMISS_SSS] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [ACCELEROMETERXMS,ACCELEROMETERYMS,ACCELEROMETERZMS,GRAVITYXMS,GRAVITYYMS,GRAVITYZMS,MAGNETICFIELDXT,MAGNETICFIELDYT,MAGNETICFIELDZT,ORIENTATIONZAZIMUTH,ORIENTATIONXPITCH,ORIENTATIONYROLL,LOCATIONLATITUDE,LOCATIONLONGITUDE,LOCATIONALTITUDEM,LOCATIONALTITUDEGOOGLEM,LOCATIONSPEEDKMH,LOCATIONACCURACYM,LOCATIONORIENTATION,SATELLITESINRANGE,TIMESINCESTARTINMS,YYYYMODDHHMISS_SSS]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [ACCELEROMETERXMS,ACCELEROMETERYMS,ACCELEROMETERZMS,GRAVITYXMS,GRAVITYYMS,GRAVITYZMS,MAGNETICFIELDXT,MAGNETICFIELDYT,MAGNETICFIELDZT,ORIENTATIONZAZIMUTH,ORIENTATIONXPITCH,ORIENTATIONYROLL,LOCATIONLATITUDE,LOCATIONLONGITUDE,LOCATIONALTITUDEM,LOCATIONALTITUDEGOOGLEM,LOCATIONSPEEDKMH,LOCATIONACCURACYM,LOCATIONORIENTATION,SATELLITESINRANGE,TIMESINCESTARTINMS,YYYYMODDHHMISS_SSS]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [ACCELEROMETERXms,ACCELEROMETERYms,ACCELEROMETERZms,GRAVITYXms,GRAVITYYms,GRAVITYZms,MAGNETICFIELDXT,MAGNETICFIELDYT,MAGNETICFIELDZT,ORIENTATIONZazimuth,ORIENTATIONXpitch,ORIENTATIONYroll,LOCATIONLatitude,LOCATIONLongitude,LOCATIONAltitudem,LOCATIONAltitudegooglem,LOCATIONSpeedKmh,LOCATIONAccuracym,LOCATIONORIENTATION,Satellitesinrange,Timesincestartinms,YYYYMODDHHMISS_SSS] = importfile('Sensor_record_20170402_180613_AndroSensor.csv',2, 2439);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/04/02 19:51:33

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21]);
rawCellColumns = raw(:, [19,20,22]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
ACCELEROMETERXms = cell2mat(rawNumericColumns(:, 1));
ACCELEROMETERYms = cell2mat(rawNumericColumns(:, 2));
ACCELEROMETERZms = cell2mat(rawNumericColumns(:, 3));
GRAVITYXms = cell2mat(rawNumericColumns(:, 4));
GRAVITYYms = cell2mat(rawNumericColumns(:, 5));
GRAVITYZms = cell2mat(rawNumericColumns(:, 6));
MAGNETICFIELDXT = cell2mat(rawNumericColumns(:, 7));
MAGNETICFIELDYT = cell2mat(rawNumericColumns(:, 8));
MAGNETICFIELDZT = cell2mat(rawNumericColumns(:, 9));
ORIENTATIONZazimuth = cell2mat(rawNumericColumns(:, 10));
ORIENTATIONXpitch = cell2mat(rawNumericColumns(:, 11));
ORIENTATIONYroll = cell2mat(rawNumericColumns(:, 12));
LOCATIONLatitude = cell2mat(rawNumericColumns(:, 13));
LOCATIONLongitude = cell2mat(rawNumericColumns(:, 14));
LOCATIONAltitudem = cell2mat(rawNumericColumns(:, 15));
LOCATIONAltitudegooglem = cell2mat(rawNumericColumns(:, 16));
LOCATIONSpeedKmh = cell2mat(rawNumericColumns(:, 17));
LOCATIONAccuracym = cell2mat(rawNumericColumns(:, 18));
LOCATIONORIENTATION = rawCellColumns(:, 1);
Satellitesinrange = rawCellColumns(:, 2);
Timesincestartinms = cell2mat(rawNumericColumns(:, 19));
YYYYMODDHHMISS_SSS = rawCellColumns(:, 3);


